### ISSUE TITLE
Add copyrights/license information

### ISSUE THREAD

**Issue by vazhnov** [da-nie/SimplyVGAVideoCard#1]
Здравствуйте!
Добавьте, пожалуйста, файл `LICENSE`, чтобы было понятно можно ли распространять ваш код и какие условия. Было бы здорово увидеть одну из популярных open source лицензий.

**Comment by da-nie** [comment]
Здравствуйте. Мне когда-то посоветовали лицензию MIT, как наиболее разрешающую делать с кодом всё, что угодно кому угодно. Вот только, что надо в файл license вписать для неё?

**Comment by vazhnov** [comment]
А вы попробуйте через WEB-интерфейс github начать создавать файл `LICENSE`, там дальше вам github всё подскажет!

**Comment by vazhnov** [comment]
Вижу файл с лицензией MIT.
Спасибо!
